package com.mydomain.scm.model;
// Generated 13 Jan 2010 3:10:57 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContactInGroupId generated by hbm2java
 */
@Embeddable
public class ContactInGroupId implements java.io.Serializable {

	private int contactGroup;
	private int contact;

	public ContactInGroupId() {
	}

	public ContactInGroupId(int contactGroup, int contact) {
		this.contactGroup = contactGroup;
		this.contact = contact;
	}

	@Column(name = "ContactGroup", nullable = false)
	public int getContactGroup() {
		return this.contactGroup;
	}

	public void setContactGroup(int contactGroup) {
		this.contactGroup = contactGroup;
	}

	@Column(name = "Contact", nullable = false)
	public int getContact() {
		return this.contact;
	}

	public void setContact(int contact) {
		this.contact = contact;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContactInGroupId))
			return false;
		ContactInGroupId castOther = (ContactInGroupId) other;

		return (this.getContactGroup() == castOther.getContactGroup())
				&& (this.getContact() == castOther.getContact());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContactGroup();
		result = 37 * result + this.getContact();
		return result;
	}

}
