package com.mydomain.scm.model;
// Generated 13 Jan 2010 3:10:57 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ContactField generated by hbm2java
 */
@Entity
@Table(name = "contact_field", catalog = "advcm_db")
public class ContactField implements java.io.Serializable {

	private Integer id;
	private Contact contact;
	private String label;
	private String value;
	private String type;

	public ContactField() {
	}

	public ContactField(Contact contact, String label, String value, String type) {
		this.contact = contact;
		this.label = label;
		this.value = value;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ContactId", nullable = false)
	@NotNull
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "label", nullable = false)
	@NotNull
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "value", nullable = false)
	@NotNull
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "type", nullable = false)
	@NotNull
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
